<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8" />
  <title>LoL Collector - Comming Soon </title>
  <link rel="stylesheet" href="style.css" />
  <meta name="description" content="LoL Collector">
  <meta name="author" content="LampLighter Team">
  <link rel="shortcut icon" href="#"> <!-- falta o icone-->
  <link href="../libs/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="../libs/font-awesome/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
  <section class="container-fluid">
    <header>
      <h1 class="text-center"> Olá, invocador! </h1>
    </header>
    <div class="jumbotron">
      <div class="about">
        <a href="" target="_blank">Curta a fanpage no Facebook <i class="fa fa-facebook"></i></a>
        <a href="" target="_blank">Curta o projeto no Github <i class="fa fa-github"></i></a>
      </div>
    </div>
    <footer>
      <p>
        <i class="fa fa-code"></i> with <i class="fa fa-heart"></i> by <a href="chroda.com.br" target="_blank">chroda</a>
      </p>
    </footer>
  </section>
</body>
</html>
